### ISSUE TITLE
Add possibility to process GSPs in extra included dirs.

### ISSUE THREAD

**Issue by nkovalenko93** [chrismair/GrailsCodeNarcPlugin#23]
I have "plugins" folder in my Grails project that contains internal Grails plugins.
I want to process GSPs too in that internal plugins.
We can modify "scripts/Codenarc.groovy" line 243 like that:
```
for (includeDir in config.extraIncludeDirs) {
        includes << "$includeDir/**/*.groovy"
        if (getConfigBoolean(config, 'processExtraIncludeDirsViews', false)) {
            includes << "$includeDir/**/*.gsp"
        }
}
```

**Comment by nkovalenko93** [comment]
Made a [pull request](https://github.com/chrismair/GrailsCodeNarcPlugin/pull/25).

**Comment by chrismair** [comment]
We are on a roughly 6 month release cadence, so I would expect the 1.6 release around May.
