### ISSUE TITLE
How to fail Grails build on error?

### ISSUE THREAD

**Issue by nkovalenko93** [chrismair/GrailsCodeNarcPlugin#24]
I have a Grails application.
I run "grails codenarc".
I want to fail process after report is generated if there are some errors.

How to do this? My process is always finishes successfully even there are a lot of errors.

**Comment by chrismair** [comment]
Looks like this will require a code change, to expose the CodeNarc Ant Task `failOnError` config property. But I agree that is worth doing.

**Comment by nkovalenko-sc** [comment]
Can I help you with that? I tried to make a pull request but I have no enough responsibilities to create branch in your repository.

**Comment by nkovalenko93** [comment]
Can I help you with that? I tried to make a pull request but I have no enough responsibilities to create branch in your repository.

**Comment by chrismair** [comment]
I think you need to fork the repo first and then create the pull request:
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by nkovalenko93** [comment]
Oh, I could just make this:
```
codenarc.maxPriority1Violations=0 // Maximum of 1-level errors to not to fail build
codenarc.maxPriority2Violations=10 // Maximum of 2-level errors to not to fail build
codenarc.maxPriority3Violations=20 // Maximum of 3-level errors to not to fail build
```

**Comment by chrismair** [comment]
Ugh, yes, I should have remembered that. No need for a code change.
